format: 
  html: default
  beamer:
    theme: Madrid
    slide-level: 2
    keep-tex: true
    toc: false
    incremental: false
  docx: 
    crossref:
      ref-hyperlink: true
    keep-md: true
    notes-after-punctuation: true
    toc: true
    echo: false
    # fig-format: svg # seems to break things
    fig-dpi: 600
    toc-depth: 4
    cap-location: top
    fig-cap-location: top
    appendix-title: "Sup."
    tbl-cap-location: top
    number-sections: false
    number-depth: 3
    link-citations: true
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    embed-resources: false
    appendix-style: plain
    mainfont: serif
  revealjs: default
