---
title: "Longitudinal analysis of Shigella"
format: 
  pdf:
    number-sections: true
    number-depth: 2
    number-offset: [0, 0]
editor: visual
output:
  pdf_document:
    orientation: landscape
---

## Introduction

```{r setup, include=FALSE,echo=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(gridExtra)
library(haven)
library(knitr)
library(plotly)
library(kableExtra)
library(tidyr)
library(arsenal)
library(dplyr)
library(forcats)
library(huxtable)
library(magrittr)
library(parameters)
library(kableExtra)
library(ggplot2)
library(ggeasy)
library(scales)
library(plotly)
library(patchwork)
library(tidyverse)
library(gtsummary)
library(readxl)

library(serocalculator)
library(runjags)
library(coda)
library(ggmcmc)
library(here)

```


### Data description
- Step 2: Load the Dataset

```{r}
df <- read_excel("3.8.2024 Compiled Shigella data.xlsx", 
                      sheet = "Compiled")
```

- Step 3: Understand the Structure of the Dataset

```{r}
# View the structure of the dataset
str(df)

# View the first few rows of the dataset
head(df)

# View a summary of the dataset
summary(df)
```

- Step 4: Handle Missing Values

```{r}
colSums(is.na(df))

```


## Exploratory Data Analysis

```{r}
# select longitudinal dataset from complied dataset

df_sosar<-df%>%filter(study_name=="SOSAR")

# split the data by isotype

df_sosar_IgA<-df_sosar%>%filter(isotype_name=="IgA")

df_sosar_IgG<-df_sosar%>%filter(isotype_name=="IgG")


```


### Plotting quantitative response change over time

```{r}
# plotting how quantitative response change over time within individuals


# Check the number of observations per sid
df_summary_IgA <- df_sosar_IgA %>%
  group_by(sid) %>%
  summarize(count = n()) %>%
  filter(count > 1)

df_summary_IgA
```
Checking unique sample identification number (sid) is important. There are 48 sid in this SOSAR study.

```{r}
# Filter the original dataframe to include only individuals with more than one observation
df_filtered_IgA <- df_sosar_IgA %>%
  filter(sid %in% df_summary_IgA$sid)

# Plotting ipab_MFI over time for each individual
ggplot(df_filtered_IgA, aes(x = timepoint, y = ipab_MFI, group = sid, color = sid)) +
  geom_line() +
  geom_point() +
  labs(title = "Change in ipab_MFI Over Time",
       x = "Timepoint",
       y = "ipab_MFI",
       color = "Individual ID") +
  theme_minimal()
```



## Understand the longitudinal antibody decay


```{r, echo=FALSE, message=FALSE}
file.mod <- here::here()  %>% fs::path("inst/extdata/model.jags.2.r")
```


```{r, echo=FALSE, message=FALSE}
# manipulating shigella data for applying dcm code
dL<-df_sosar%>%select(isotype_name,sid,cohort,age,treatment,timepoint)%>%
  mutate(index_id=sid,antigen_iso=isotype_name,visit=timepoint)

dL<-dL%>%group_by(index_id, antigen_iso) %>%# Group data by individual
   arrange(visit) %>%  # Sort data by visit within each group
   mutate(visit_num = rank(visit, ties.method = "first")) %>%
   ungroup()
```



```{r, echo=FALSE, message=FALSE}
#subset data for checking
dL_sub <- dL %>%
 filter(index_id %in% sample(unique(index_id), 20))
```



```{r, echo=FALSE, message=FALSE}
# Construct the path to "prep_data.r" using here
prep_data_path <- here::here("R", "prep_data.r")
prep_priors_path <- here::here("R", "prep_priors.R")

# Source the file to load the prep_data function
source(prep_data_path)
source(prep_priors_path)

#prepare data for modeline
longdata <- prep_data(dL_sub)
priors <- prep_priors(max_antigens = longdata$n_antigen_isos)
```


```{r, echo=FALSE, message=FALSE}

```
