---
title: "sim_case_data analysis"
author: "Samuel Schildhauer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    toc_float: true
    #number_sections: true  ## if you want number sections at each table header
    #theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
    code_folding: hide
---
  
### Loading packages
```{r  setup, error = F, warning = F, }
library(dplyr)
library(tidyverse)
library(serocalculator)
library(gridExtra)
library(serodynamics)

knitr::opts_chunk$set(echo = TRUE)


```


### Plotting raw data  
```{r error = F, warning = F}

autoplot(serodynamics::nepal_sees)

```


```{r error = F, warning = F}

#running data
nepal_sees_output <- run_serodynamics(data = serodynamics::nepal_sees,
                                      nchain = 4,
                                      nadapt = 100,
                                      nburn = 100,
                                      nmc = 500,
                                      niter = 2000,
                                      with_pop_params = TRUE)

```


## Plotting the predictive distribution
```{r error = F, warning = F, }
plot_serocurve(nepal_sees_output, log_y = TRUE)
```

## Plotting the population distribution
```{r error = F, warning = F, }
plot_serocurve(nepal_sees_output, log_y = TRUE, param_source = "population")

```


## Simulating case data
```{r error = F, warning = F, }


nepal_sees_prep <- nepal_sees_output %>%
  filter(Subject == "newperson") %>%
  spread(Parameter, value) %>%
  rename("r" = "shape",
         "antigen_iso" = "Iso_type") %>%
  group_by(antigen_iso) %>%
  mutate(iter = row_number()) 
# as_sr_params()


# Finding number of cases from original data set
n <- length(unique(nepal_sees$id))
antigen_isos <- unique(nepal_sees$antigen_iso)

# Simulating data
simulated_data <- sim_case_data(n = n,
                                   curve_params = nepal_sees_prep,
                                   antigen_isos = antigen_isos,
                                   followup_interval = 30,
                                   followup_variance = 30,
                                   noise_sd = 0.3)


```

### Plotting simulated data
```{r error = F, warning = F, }
autoplot(simulated_data)
```

### Running serodynamics on simulated data
```{r error = F, warning = F, }

# simulated_data <- simulated_data %>%
#   as_case_data(id_var = "id",
#                biomarker_var = "antigen_iso",
#                value_var = "value",
#                time_in_days = "timeindays")
# n_select <- c("1", "5", "10", "15", "30", "50", "100", "150")
# set.seed(15)
# sero_list <- list()
# for (i in n_select) {
#   sampled_n <- sample(unique(simulated_data$id), as.numeric(i))
#   simulated_run <- simulated_data %>%
#     filter(id %in% sampled_n) %>%
#     select(id, timeindays, antigen_iso, value, visit_num)
#     sero_run <- run_serodynamics(data = simulated_run,
#                                         decay_type = "power",
#                                         nchain = 4,
#                                         nadapt = 100,
#                                         nburn = 100,
#                                         nmc = 500,
#                                         niter = 2000,
#                                         with_pop_params = TRUE)
#   sero_list[[i]] <- sero_run %>%
#     mutate(Stratification = i)
# }
# saveRDS(sero_list, "~/projects/GitHub/serodynamics/inst/extdata/sim_serolist.rds")

```

### Plotting the predictive distribution
```{r error = F, warning = F, fig.height = 12}

sero_list <- readRDS("~/projects/GitHub/serodynamics/inst/extdata/sim_serolist.rds")

# Creating plots 
plot_list <- list()
for (i in n_select) {
  sim_curve <- sero_list[[i]]
  plot_dat <- rbind(sim_curve,
                    nepal_sees_output %>%
                      mutate(Stratification = "full"))
  plot_list[[i]] <- plot_serocurve(plot_dat, log_y = T, xlim = c(0, 200))
}

grid.arrange(grobs = plot_list, ncol = 2)


```